Update yaml to reflect spec update
Green-Software-Foundation/carbon-ql pull request #63
Opened 2023-07-23 17:11 UTC by jawache

2023-07-23 23:56 UTC, srini1978 requested changes
Can we separate the duration field as 1) Duration and 2) Unit . This will allow us to scale the yaml in scenarios where telemetry is for a period of 2 hours or 3 hours rather than seconds

2023-07-24 16:10 UTC, jawache commented
@srini1978 I'm very keen for the default impl to be as minimal as possible, to make demo'ing, explaining it easier - 5 mins to wow.

So perhaps we can have a default duration units of "seconds" and if you want to provide durations in different units then that's extra configuration.

```yaml
    - datetime: 2023-07-06T00:05:
      duration: 5 # defaults to seconds
      cpu: 0.11
```

@gnanakeethan is proposing a mapping field for the CSV loading to convert/provide metadata for the observations so perhaps we can use that for even manually created

So perhaps something like this?

```yaml
series:
    - datetime: 2023-07-06T00:05:
      span: 5
      cpu: 11
mapping:
  span:
    units: minutes # field is in minutes
    to: duration # field needs to be converted to "duration" for input to the IMP.
  cpu:
    units: percentage
```

I like the idea of sticking to one mapping sections that works for both CSV and our static inputs. 

Thoughts?

2023-07-25 15:29 UTC, jawache commented
@srini1978 added the mapping.

2023-07-27 10:53 UTC, jawache commented
Agreed on project call

2023-07-27 10:53 UTC, merged